baseURL = 'https://r0bert.dev'
languageCode = 'en-GB'
title = 'Robert Greener'
theme = "papermod"
disqusShortname = 'r0bert-dev'
[Params]
  hideFooter = true
  comments = true
[menu]
[[menu.main]]
  identifier = "hg"
  name = "hg"
  url = "https://hg.sr.ht/~ragreener1"
  weight = 100
