baseURL = 'https://r0bert.dev'
languageCode = 'en-GB'
title = 'Robert Greener'
theme = "papermod"
disqusShortname = 'r0bert-dev'
[Params]
  hideFooter = true
  comments = true
[menu]
[[menu.main]]
  identifier = "git"
  name = "git"
  url = "https://git.r0bert.dev"
  weight = 100
